### ISSUE TITLE
Implement simple GitHub API adapter using octokit and C#

### ISSUE THREAD

**Issue by Konard** [linksplatform/Bot#71]
Library that should be used for implementation: https://github.com/octokit/octokit.net

Right now Doublets available only from C# so the `octokit.net` library should be used to create C#-version of the bot.

This simple bot should be able to be connected to any repository.
It should be able to react to creation of issue `hello world`.
The default reaction (that should be replaceable) is:
1. Creates `program.c` or file in other language with program that outputs `hello world` into standard output
2. Creates `.github/workflows/CD.yml` file with command to build and run this program
Once GitHub Actions completes all steps of `CD.yml` file bot should close `hello world` issue.

The GitHub bot should be added to `csharp` folder in this repository.

500 RUB reward can be claimed by anyone who completes this task.

**Comment by FirstAfterGod2501** [comment]
Returned the award to the LinksPlatform budget

**Comment by Konard** [comment]
> Returned the award to the LinksPlatform budget

Thank you. This reward will be used for other LinksPlatform tasks.
