### ISSUE TITLE
Split data layer to separate class

### ISSUE THREAD

**Issue by Konard** [linksplatform/Bot#83]
1000 RUB reward can be claimed by anyone who completes this task.

It can be named DataService or DataLayer or DataApi or something better.
All usages of [BetterBotBase](https://github.com/linksplatform/Bot/blob/master/python/__main__.py#L2) should be removed from the main (V) class.
These usages should be moved to a separate class (with separate file).

**Comment by heprajicfyz1** [comment]
+= github.com/heprajicfyz1

**Comment by dry71** [comment]
https://github.com/linksplatform/Bot/blob/DataService/python/DataService.py

**Comment by Konard** [comment]
Rewards are:
700 RUB for @dry71 
300 RUB for @Ethosa
